<TR> 
	<TD COLSPAN="2">&nbsp;</TD>
</TR>
<TR> 
	<TD COLSPAN="2" CLASS="contenido"><STRONG>B&uacute;squeda de Alumnos</STRONG></TD>
</TR>
<TR> 
	<TD COLSPAN="2">
		<TABLE WIDTH="100%" BORDER="1" CELLPADDING="0" CELLSPACING="0" BORDERCOLOR="#F1F1F1">
			<TR>
				<TD>
					<FORM ACTION="buscar.php" METHOD="get" NAME="formulario" onSubmit="return validarFormulario();">
						<TABLE WIDTH="100%" BORDER="0" CELLPADDING="0" CELLSPACING="0">
							<TR> 
								<TD COLSPAN="2">&nbsp;</TD>
							</TR>
							<TR> 
								<TD WIDTH="20%" CLASS="formlabel">Nombres:</TD>
								<TD WIDTH="80%"><INPUT NAME="nombres" TYPE="text" CLASS="formtextfield" MAXLENGTH="50" TITLE="Primer o segundo nombre del alumno" TABINDEX="1"></TD>
							</TR>
							<TR> 
								<TD WIDTH="20%" CLASS="formlabel">Apellidos:</TD>
								<TD WIDTH="80%"><INPUT NAME="apellidos" TYPE="text" CLASS="formtextfield" MAXLENGTH="50" TITLE="Apellido paterno o materno del alumno" TABINDEX="1"></TD>
							</TR>
							<TR> 
								<TD>&nbsp;</TD>
								<TD><input name="buscar" type="submit" class="formbutton" value="Buscar" TITLE="Buscar al alumno" TABINDEX="1"></TD>
							</TR>
							<TR> 
								<TD colspan="2"><INPUT TYPE="hidden" NAME="pagina" VALUE="1"></TD>
							</TR>
						</TABLE>
					</FORM>
				</TD>
			</TR>
		</TABLE>
	</TD>
</TR>
<TR> 
	<TD COLSPAN="2">&nbsp;</TD>
</TR>