<TABLE WIDTH="100%" BORDER="0" CELLPADDING="0" CELLSPACING="0">
	<TR>
		<TD BACKGROUND="<?PHP echo $nivel ?>/librerias/bgbox.gif" CLASS="tema"><A HREF="JavaScript:window.external.AddFavorite('http://www.escuelaingecomp.tk','Escuela Ingeniería en Computación');" TITLE="Agregar a Mis Favoritos"><IMG SRC="<?PHP echo $nivel ?>/librerias/icofavoritos.gif" WIDTH="20" HEIGHT="12" BORDER="0">Agregar a Favoritos</A></TD>
	</TR>
	<TR>
		<TD BACKGROUND="<?PHP echo $nivel ?>/librerias/bgbox.gif" CLASS="tema"><A HREF="JavaScript:window.print();" TITLE="Imprimir esta P&aacute;gina"><IMG SRC="<?PHP echo $nivel ?>/librerias/icoimprimir.gif" WIDTH="20" HEIGHT="12" BORDER="0">Imprimir P&aacute;gina</A></TD>
	</TR>
	<TR>
		<TD BACKGROUND="<?PHP echo $nivel ?>/librerias/bgbox.gif" CLASS="tema"><A HREF="index.php" onClick="this.style.behavior='url(#default#homepage)';this.setHomePage('http://www.escuelaingecomp.tk');" TITLE="Establecer como P&aacute;gina de Inicio"><IMG SRC="<?PHP echo $nivel ?>/librerias/icoinicio.gif" WIDTH="20" HEIGHT="12" BORDER="0">P&aacute;gina de Inicio</A></TD>
	</TR>
	<TR>
		<TD BACKGROUND="<?PHP echo $nivel ?>/librerias/bgbox.gif" CLASS="tema"><A HREF="index.php" onClick="openWindow('<?PHP echo $nivel ?>/herramientas/recomendar.php','RecomendarWeb','width=400,height=380');" TITLE="Recomendar este Web a un Amigo"><IMG SRC="<?PHP echo $nivel ?>/librerias/icorecomendar.gif" WIDTH="20" HEIGHT="12" BORDER="0">Recomendar este Web</A></TD>
	</TR>
</TABLE>