<TABLE WIDTH="100%" BORDER="0" MM_NOCONVERT="true">
	<TR>
		<TD CLASS="referencia"><A HREF="mailto:ejeltsch@userena.cl" TITLE="ejeltsch@userena.cl">Director de Escuela</A> | <A HREF="mailto:cecingecomp@gmail.com" TITLE="cecingecomp@gmail.com">CEC</A></TD>
	</TR>
	<TR>
		<TD CLASS="copyright">Copyright &copy; <?PHP echo date("Y"); ?> Escuela Ingenier&iacute;a en Computaci&oacute;n de la ULS. Todos los derechos reservados.</TD>
	</TR>
</TABLE>