<TABLE WIDTH="100%" BORDER="0" CELLPADDING="0" CELLSPACING="0" MM_NOCONVERT="TRUE">
	<TR>
		<TD WIDTH="76%" CLASS="ubicacion"><?PHP echo $ubicacion ?></TD>
		<TD ROWSPAN="2" WIDTH="24%" VALIGN="TOP"><IMG SRC="<?PHP echo $imagen ?>" WIDTH="110" HEIGHT="45"></TD>
	</TR>
	<TR>
		<TD WIDTH="76%" CLASS="titulo"><?PHP echo $titulo ?></TD>
	</TR>
	<TR>
		<TD COLSPAN="2"><IMG SRC="<?PHP echo $pixel ?>" WIDTH="460" HEIGHT="1"></TD>
	</TR>
</TABLE>